#!/bin/bash

# Load one deployment profile without coupling the reusable project to a
# particular LAN. Callers must set SQUID_DIR before sourcing this file.
if [ -z "${SQUID_DIR:-}" ]; then
    echo "ERROR: SQUID_DIR must be set before loading deployment settings." >&2
    return 1 2>/dev/null || exit 1
fi

SQUID_DEPLOYMENT_DIR="${SQUID_DEPLOYMENT_DIR:-${SQUID_DIR}/deployments/local}"
DEPLOYMENT_ENV="${SQUID_DEPLOYMENT_DIR}/deployment.env"

if [ ! -f "${DEPLOYMENT_ENV}" ]; then
    echo "ERROR: Deployment profile not found: ${DEPLOYMENT_ENV}" >&2
    echo "Create it with:" >&2
    echo "  cp -R ${SQUID_DIR}/deployments/example ${SQUID_DEPLOYMENT_DIR}" >&2
    echo "Then edit deployment.env, proxy-hosts.conf, and devices.list." >&2
    return 1 2>/dev/null || exit 1
fi

set -a
# deployment.env is a trusted, administrator-owned shell environment file.
# shellcheck disable=SC1090
. "${DEPLOYMENT_ENV}"
set +a

: "${QNAP_IP:?QNAP_IP is required in ${DEPLOYMENT_ENV}}"
: "${QNAP_USER:?QNAP_USER is required in ${DEPLOYMENT_ENV}}"
: "${ROUTER_IP:?ROUTER_IP is required in ${DEPLOYMENT_ENV}}"
: "${SQUID_PROXY_IP:?SQUID_PROXY_IP is required in ${DEPLOYMENT_ENV}}"
: "${WEBUI_IP:?WEBUI_IP is required in ${DEPLOYMENT_ENV}}"

TIMEZONE="${TIMEZONE:-UTC}"
QNAP_DOCKER="${QNAP_DOCKER:-/usr/bin/docker}"
QNAP_CONTAINER_ROOT="${QNAP_CONTAINER_ROOT:-/share/Container}"
QNAP_CERT_DOWNLOAD_DIR="${QNAP_CERT_DOWNLOAD_DIR:-${QNAP_CONTAINER_ROOT}/cert-downloads}"
QNAP_DOCKER_NETWORK="${QNAP_DOCKER_NETWORK:-bridge}"
QNAP_DOCKER_HOME_ROOT="${QNAP_DOCKER_HOME_ROOT:-/tmp}"
ROUTER_USER="${ROUTER_USER:-${QNAP_USER}}"
ROUTER_LAN_INTERFACE="${ROUTER_LAN_INTERFACE:-br0}"
ROUTER_ROUTE_TABLE="${ROUTER_ROUTE_TABLE:-150}"
ROUTER_MARK="${ROUTER_MARK:-0x5000}"
ROUTER_FIREWALL_SCRIPT="${ROUTER_FIREWALL_SCRIPT:-/jffs/scripts/firewall-start}"
SQUID_CONTAINER_NAME="${SQUID_CONTAINER_NAME:-squid-proxy}"
WEBUI_CONTAINER_NAME="${WEBUI_CONTAINER_NAME:-squid-webui}"
SQUID_IMAGE="${SQUID_IMAGE:-squid-ssl:latest}"
WEBUI_IMAGE="${WEBUI_IMAGE:-squid-webui:latest}"
SQUID_PROXY_PORT="${SQUID_PROXY_PORT:-3128}"
SQUID_HTTP_PORT="${SQUID_HTTP_PORT:-3129}"
SQUID_HTTPS_PORT="${SQUID_HTTPS_PORT:-3130}"
SQUID_DNS_SERVERS="${SQUID_DNS_SERVERS:-8.8.8.8}"
WEBUI_PORT="${WEBUI_PORT:-3131}"
WEBUI_PUBLIC_URL="${WEBUI_PUBLIC_URL:-http://${WEBUI_IP}:${WEBUI_PORT}}"
LOCAL_NETWORKS="${LOCAL_NETWORKS:-192.0.2.0/24}"
NO_PROXY_NETWORKS="${NO_PROXY_NETWORKS:-localhost,127.0.0.1,local,.local}"
ADMIN_CLIENT_IPS="${ADMIN_CLIENT_IPS:-}"
DEFAULT_CLIENT_IP="${DEFAULT_CLIENT_IP:-}"
DEFAULT_CLIENT_NAME="${DEFAULT_CLIENT_NAME:-remote-ubuntu}"
CERT_SUBJECT="${CERT_SUBJECT:-/C=US/O=Home LAN/OU=Proxy/CN=squid.local}"
CERT_NAME="${CERT_NAME:-squid.local}"

QNAP_SERVER="${QNAP_USER}@${QNAP_IP}"
ROUTER_SERVER="${ROUTER_USER}@${ROUTER_IP}"
WEBUI_URL="${WEBUI_PUBLIC_URL}"
PAC_URL="${WEBUI_PUBLIC_URL}/proxy.pac"
EXPLICIT_PROXY_URL="http://${SQUID_PROXY_IP}:${SQUID_PROXY_PORT}"

PROXY_HOSTS_CONF="${PROXY_HOSTS_CONF:-${SQUID_DEPLOYMENT_DIR}/proxy-hosts.conf}"
DEVICES_LIST="${DEVICES_LIST:-${SQUID_DEPLOYMENT_DIR}/devices.list}"
CERT_DIR="${CERT_DIR:-${SQUID_DEPLOYMENT_DIR}/certs}"
BLOCKLIST_DIR="${BLOCKLIST_DIR:-${SQUID_DIR}/block-lists}"

export SQUID_DEPLOYMENT_DIR DEPLOYMENT_ENV TIMEZONE QNAP_IP QNAP_USER QNAP_DOCKER
export QNAP_CONTAINER_ROOT QNAP_CERT_DOWNLOAD_DIR QNAP_DOCKER_NETWORK
export ROUTER_IP ROUTER_USER ROUTER_LAN_INTERFACE ROUTER_ROUTE_TABLE ROUTER_MARK
export ROUTER_FIREWALL_SCRIPT SQUID_CONTAINER_NAME WEBUI_CONTAINER_NAME
export SQUID_IMAGE WEBUI_IMAGE SQUID_PROXY_IP SQUID_PROXY_PORT SQUID_HTTP_PORT
export SQUID_HTTPS_PORT SQUID_DNS_SERVERS WEBUI_IP WEBUI_PORT WEBUI_PUBLIC_URL
export LOCAL_NETWORKS NO_PROXY_NETWORKS ADMIN_CLIENT_IPS CERT_SUBJECT CERT_NAME
export DEFAULT_CLIENT_IP DEFAULT_CLIENT_NAME PROXY_HOSTS_CONF DEVICES_LIST CERT_DIR
export BLOCKLIST_DIR QNAP_DOCKER_HOME_ROOT
