import os
import json
import secrets
import subprocess
import paramiko
from passlib.hash import md5_crypt, sha512_crypt, sha256_crypt, des_crypt
from flask import Flask, render_template, request, jsonify, session

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", secrets.token_hex(24))

# Configuration paths (inside container / host)
SQUID_CONFIG_DIR = os.environ.get("SQUID_CONFIG_DIR", "/etc/squid/configs")
SQUID_BLOCKLIST_DIR = os.environ.get("SQUID_BLOCKLIST_DIR", "/etc/squid/block-lists")
ROUTER_HOSTS_CONF = os.environ.get("ROUTER_HOSTS_CONF", "/etc/squid/router/proxy-hosts.conf")

RULES_JSON_PATH = os.path.join(SQUID_CONFIG_DIR, "rules.json")
RULES_ACL_PATH = os.path.join(SQUID_CONFIG_DIR, "rules.acl")

QNAP_IP = os.environ.get("QNAP_IP", "192.168.1.2")
SQUID_CONTAINER_NAME = os.environ.get("SQUID_CONTAINER_NAME", "squid-proxy")

DAY_MAP = {
    "Sunday": "S",
    "Monday": "M",
    "Tuesday": "T",
    "Wednesday": "W",
    "Thursday": "H",
    "Friday": "F",
    "Saturday": "A"
}


def is_authenticated():
    return session.get("authenticated", False)


def verify_shadow_password(username, password):
    """Verify password directly against mounted QNAP shadow file."""
    shadow_paths = [
        "/host_etc/shadow",
        "/host_etc/config/shadow",
        "/etc/shadow",
        "/etc/config/shadow"
    ]
    for path in shadow_paths:
        if os.path.exists(path):
            try:
                with open(path, "r") as f:
                    for line in f:
                        parts = line.strip().split(":")
                        if len(parts) >= 2 and parts[0] == username:
                            stored_hash = parts[1]
                            if stored_hash in ["*", "!", ""]:
                                return False

                            if stored_hash.startswith("$1$"):
                                return md5_crypt.verify(password, stored_hash)
                            elif stored_hash.startswith("$6$"):
                                return sha512_crypt.verify(password, stored_hash)
                            elif stored_hash.startswith("$5$"):
                                return sha256_crypt.verify(password, stored_hash)
                            else:
                                return des_crypt.verify(password, stored_hash)
            except Exception as e:
                print(f"Error reading shadow file at {path}: {e}")
    return False


def verify_nas_credentials(username, password):
    """Verify user credentials via shadow file or SSH fallback."""
    if verify_shadow_password(username, password):
        return True

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    try:
        target = QNAP_IP
        ssh.connect(
            target,
            port=22,
            username=username,
            password=password,
            look_for_keys=False,
            allow_agent=False,
            timeout=5
        )
        ssh.close()
        return True
    except Exception as e:
        print(f"Authentication failed for user '{username}' on target {QNAP_IP}: {e}")
        return False


def load_rules():
    if os.path.exists(RULES_JSON_PATH):
        try:
            with open(RULES_JSON_PATH, "r") as f:
                return json.load(f)
        except Exception as e:
            print(f"Error loading rules.json: {e}")
    return []


def save_rules(rules):
    os.makedirs(os.path.dirname(RULES_JSON_PATH), exist_ok=True)
    with open(RULES_JSON_PATH, "w") as f:
        json.dump(rules, f, indent=2)
    compile_squid_acls(rules)


def compile_squid_acls(rules):
    """Compile rules list into Squid ACL file (rules.acl)."""
    acl_lines = [
        "# ===========================================================",
        "# AUTO-GENERATED BY SQUID WEB UI - DO NOT EDIT MANUALLY",
        "# ===========================================================",
        ""
    ]

    for rule in rules:
        if not rule.get("enabled", True):
            continue

        rule_id = rule.get("id")
        rule_name = rule.get("name", "Unnamed Rule")
        src_ip = rule.get("source_ip")
        blocklist = rule.get("blocklist")
        days = rule.get("days", [])
        time_start = rule.get("time_start", "00:00")
        time_end = rule.get("time_end", "23:59")
        policy = rule.get("policy", "allow_during_slot")

        if not src_ip or not blocklist:
            continue

        acl_lines.append(f"# Rule: {rule_name} ({rule_id})")

        # Define Source IP ACL
        acl_lines.append(f"acl src_{rule_id} src {src_ip}")

        # Define Domain Blocklist ACL
        blocklist_path = f"/etc/squid/block-lists/{blocklist}"
        acl_lines.append(f"acl list_{rule_id} dstdomain \"{blocklist_path}\"")

        # Define Time ACL if days/times are specified
        day_codes = "".join([DAY_MAP[d] for d in days if d in DAY_MAP])
        if not day_codes:
            day_codes = "SMWTHFA" # All days

        acl_lines.append(f"acl time_{rule_id} time {day_codes} {time_start}-{time_end}")

        # Policy Access Rules
        if policy == "allow_during_slot":
            # Allow access to domain during scheduled time slot, block outside of it
            acl_lines.append(f"http_access allow src_{rule_id} list_{rule_id} time_{rule_id}")
            acl_lines.append(f"http_access deny src_{rule_id} list_{rule_id}")
        elif policy == "block_during_slot":
            # Block access to domain during scheduled time slot, allow otherwise
            acl_lines.append(f"http_access deny src_{rule_id} list_{rule_id} time_{rule_id}")

        acl_lines.append("")

    os.makedirs(os.path.dirname(RULES_ACL_PATH), exist_ok=True)
    with open(RULES_ACL_PATH, "w") as f:
        f.write("\n".join(acl_lines) + "\n")

    reload_squid()


def reload_squid():
    """Trigger squid reconfigure inside container."""
    try:
        cmd = ["docker", "exec", SQUID_CONTAINER_NAME, "squid", "-k", "reconfigure"]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode == 0:
            print("Squid reconfigured successfully.")
        else:
            print(f"Squid reconfigure output: {res.stderr or res.stdout}")
    except Exception as e:
        print(f"Failed to reload Squid: {e}")


# --- API ENDPOINTS ---

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/auth/status", methods=["GET"])
def auth_status():
    return jsonify({"authenticated": is_authenticated(), "user": session.get("username", "")})


@app.route("/api/login", methods=["POST"])
def login():
    data = request.json or {}
    username = data.get("username", "").strip()
    password = data.get("password", "").strip()

    if not username or not password:
        return jsonify({"success": False, "error": "Username and password required"}), 400

    if verify_nas_credentials(username, password):
        session["authenticated"] = True
        session["username"] = username
        return jsonify({"success": True})
    else:
        return jsonify({"success": False, "error": "Invalid NAS Username or Password"}), 401


@app.route("/api/logout", methods=["POST"])
def logout():
    session.clear()
    return jsonify({"success": True})


@app.route("/api/hosts", methods=["GET"])
def get_hosts():
    if not is_authenticated():
        return jsonify({"error": "Unauthorized"}), 401

    hosts = []
    if os.path.exists(ROUTER_HOSTS_CONF):
        try:
            with open(ROUTER_HOSTS_CONF, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        parts = line.split()
                        if len(parts) >= 2:
                            hosts.append({"ip": parts[0], "hostname": parts[1]})
        except Exception as e:
            print(f"Error parsing proxy-hosts.conf: {e}")

    return jsonify({"hosts": hosts})


@app.route("/api/blocklists", methods=["GET"])
def get_blocklists():
    if not is_authenticated():
        return jsonify({"error": "Unauthorized"}), 401

    files = []
    if os.path.exists(SQUID_BLOCKLIST_DIR):
        try:
            for f in os.listdir(SQUID_BLOCKLIST_DIR):
                if f.endswith(".txt") and f != "domains.txt":
                    files.append(f)
            files.sort()
            # Ensure domains.txt or main blocklists are present
            if os.path.exists(os.path.join(SQUID_BLOCKLIST_DIR, "domains.txt")):
                files.insert(0, "domains.txt")
        except Exception as e:
            print(f"Error listing blocklists: {e}")

    return jsonify({"blocklists": files})


@app.route("/api/rules", methods=["GET"])
def get_rules_api():
    if not is_authenticated():
        return jsonify({"error": "Unauthorized"}), 401
    return jsonify({"rules": load_rules()})


@app.route("/api/rules", methods=["POST"])
def add_or_update_rule():
    if not is_authenticated():
        return jsonify({"error": "Unauthorized"}), 401

    data = request.json or {}
    rules = load_rules()

    rule_id = data.get("id") or f"rule_{secrets.token_hex(4)}"
    new_rule = {
        "id": rule_id,
        "name": data.get("name", "New Rule").strip(),
        "source_ip": data.get("source_ip", "").strip(),
        "source_name": data.get("source_name", "").strip(),
        "blocklist": data.get("blocklist", "").strip(),
        "days": data.get("days", []),
        "time_start": data.get("time_start", "00:00"),
        "time_end": data.get("time_end", "23:59"),
        "policy": data.get("policy", "allow_during_slot"),
        "enabled": data.get("enabled", True)
    }

    # Replace existing rule if ID matches, otherwise append
    updated = False
    for i, r in enumerate(rules):
        if r.get("id") == rule_id:
            rules[i] = new_rule
            updated = True
            break
    if not updated:
        rules.append(new_rule)

    save_rules(rules)
    return jsonify({"success": True, "rule": new_rule})


@app.route("/api/rules/<rule_id>", methods=["DELETE"])
def delete_rule(rule_id):
    if not is_authenticated():
        return jsonify({"error": "Unauthorized"}), 401

    rules = load_rules()
    rules = [r for r in rules if r.get("id") != rule_id]
    save_rules(rules)
    return jsonify({"success": True})


@app.route("/api/rules/<rule_id>/toggle", methods=["POST"])
def toggle_rule(rule_id):
    if not is_authenticated():
        return jsonify({"error": "Unauthorized"}), 401

    rules = load_rules()
    for r in rules:
        if r.get("id") == rule_id:
            r["enabled"] = not r.get("enabled", True)
            break
    save_rules(rules)
    return jsonify({"success": True})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=3131, debug=False)
